// <auto-generated />
using System;
using AddressBookTask6.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AddressBookTask6.Migrations
{
    [DbContext(typeof(AddressBookDbContext))]
    [Migration("20190730081307_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AddressBookTask6.Model.AddressBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("personId");

                    b.Property<int>("selectedIndex");

                    b.HasKey("Id");

                    b.HasIndex("personId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("AddressBookTask6.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressBookId");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.HasIndex("AddressBookId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("AddressBookTask6.Model.AddressBook", b =>
                {
                    b.HasOne("AddressBookTask6.Model.Person", "person")
                        .WithMany()
                        .HasForeignKey("personId");
                });

            modelBuilder.Entity("AddressBookTask6.Model.Person", b =>
                {
                    b.HasOne("AddressBookTask6.Model.AddressBook")
                        .WithMany("listPerson")
                        .HasForeignKey("AddressBookId");
                });
#pragma warning restore 612, 618
        }
    }
}
